from copy import deepcopy
from io import BytesIO

from django.core.files.uploadedfile import UploadedFile
from django.forms import CheckboxSelectMultiple
from django.test import TestCase
from django.utils.datastructures import MultiValueDict

from apps.blog.import_contract import MAX_SOURCE_BYTES, validate_blog_import
from apps.blog.import_forms import (
    MAX_IMAGE_AGGREGATE_BYTES,
    MAX_IMAGE_FILE_COUNT,
    BlogArticleImportReviewForm,
    BlogArticleImportUploadForm,
)
from apps.blog.import_services import resolve_blog_import_references
from apps.blog.models import AuthorProfile, BlogCategory, BlogTag


def upload(name, content=b"file", *, size=None):
    return UploadedFile(
        file=BytesIO(content),
        name=name,
        content_type="application/octet-stream",
        size=len(content) if size is None else size,
    )


def payload(*, author="oli", category="development", tags=None, publication_sites=None):
    return {
        "format": "blog-article-import",
        "version": 1,
        "article": {
            "title": "An importable article",
            "summary": "A draft summary.",
            "author": {"slug": author},
            "category": {"slug": category},
            "tags": [{"slug": value} for value in (tags or [])],
            "publication_sites": publication_sites or ["vanta_admin"],
            "blocks": [{"type": "heading", "level": 2, "text": "A section"}],
        },
        "assets": [],
        "comparisons": [],
    }


class BlogImportUploadFormTests(TestCase):
    def test_upload_form_has_the_multiple_file_widget_and_product_copy(self):
        form = BlogArticleImportUploadForm()

        self.assertTrue(form.fields["image_files"].widget.allow_multiple_selected)
        self.assertEqual(form.fields["source_file"].label, "Article JSON file")
        self.assertEqual(form.fields["image_files"].label, "Local images")
        self.assertEqual(
            form.fields["source_file"].help_text,
            "Choose one article file generated by the writing workflow.",
        )
        self.assertEqual(
            form.fields["image_files"].help_text,
            "Choose the local image files referenced by the article.",
        )
        self.assertEqual(
            form.fields["source_file"].widget.attrs["accept"],
            ".json,application/json",
        )
        self.assertIn(".png", form.fields["image_files"].widget.attrs["accept"])

    def test_upload_form_returns_a_list_and_allows_no_images(self):
        source = upload("article.json", b"{}")
        first = upload("first.png")
        second = upload("second.webp")
        files = MultiValueDict(
            {
                "source_file": [source],
                "image_files": [first, second],
            }
        )

        form = BlogArticleImportUploadForm(files=files)

        self.assertTrue(form.is_valid(), form.errors)
        self.assertEqual(form.cleaned_data["image_files"], [first, second])

        no_images = BlogArticleImportUploadForm(files=MultiValueDict({"source_file": [source]}))
        self.assertTrue(no_images.is_valid(), no_images.errors)
        self.assertEqual(no_images.cleaned_data["image_files"], [])

    def test_upload_form_enforces_source_file_count_and_aggregate_limits(self):
        oversized_source = upload(
            "article.json",
            b"{}",
            size=MAX_SOURCE_BYTES + 1,
        )
        form = BlogArticleImportUploadForm(files=MultiValueDict({"source_file": [oversized_source]}))
        self.assertFalse(form.is_valid())
        self.assertIn("The article JSON file is too large.", form.errors["source_file"])

        source = upload("article.json", b"{}")
        too_many = [upload(f"image-{index}.png") for index in range(MAX_IMAGE_FILE_COUNT + 1)]
        count_form = BlogArticleImportUploadForm(
            files=MultiValueDict({"source_file": [source], "image_files": too_many})
        )
        self.assertFalse(count_form.is_valid())
        self.assertIn("Choose no more than 50 local image files.", count_form.errors["image_files"])

        oversized_image = upload(
            "large.png",
            size=MAX_IMAGE_AGGREGATE_BYTES + 1,
        )
        aggregate_form = BlogArticleImportUploadForm(
            files=MultiValueDict({"source_file": [source], "image_files": [oversized_image]})
        )
        self.assertFalse(aggregate_form.is_valid())
        self.assertIn(
            "The selected image files are too large together.",
            aggregate_form.errors["image_files"],
        )


class BlogImportReviewFormTests(TestCase):
    def setUp(self):
        self.author = AuthorProfile.objects.create(
            user=self._new_user("author"),
            public_author_name="Oli",
            slug="oli",
        )
        self.category = BlogCategory.objects.create(name="Development", slug="development")
        self.tag = BlogTag.objects.create(name="Django", slug="django")

    def _new_user(self, username):
        from django.contrib.auth import get_user_model

        return get_user_model().objects.create_user(username=username)

    def test_review_form_preselects_exact_matches_and_exposes_source_values(self):
        source = payload(tags=["django"])
        parsed = validate_blog_import(source).parsed
        references = resolve_blog_import_references(parsed)

        form = BlogArticleImportReviewForm(parsed=parsed, references=references)

        self.assertEqual(form.initial["author"], self.author.pk)
        self.assertEqual(form.initial["category"], self.category.pk)
        self.assertEqual(form.initial["tags"], [self.tag.pk])
        self.assertEqual(form.initial["publication_sites"], ["vanta_admin"])
        self.assertEqual(form.initial["canonical_site"], "vanta_admin")
        self.assertEqual(form.source_reference_data["author"], "oli")
        self.assertEqual(form.source_reference_data["tags"], ["django"])

    def test_review_tags_use_the_shared_three_column_checkbox_widget(self):
        form = BlogArticleImportReviewForm()

        self.assertIsInstance(form.fields["tags"].widget, CheckboxSelectMultiple)
        self.assertEqual(form.fields["tags"].widget.template_name, "admin/blog/widgets/tag_checkbox_select.html")
        self.assertEqual(form.fields["tags"].widget.attrs["class"], "blog-tag-picker__choices")
        self.assertEqual(
            form.fields["publication_sites"].widget.attrs["class"],
            "blog-publication-picker__choices",
        )

    def test_unresolved_references_remain_visible_without_silent_choices(self):
        source = payload(
            author="missing-author",
            category="missing-category",
            tags=["django", "missing-tag"],
            publication_sites=["missing-site"],
        )
        parsed = validate_blog_import(source).parsed
        references = resolve_blog_import_references(parsed)

        form = BlogArticleImportReviewForm(parsed=parsed, references=references)

        self.assertEqual(
            {issue.code for issue in form.unresolved_references},
            {
                "unresolved_author",
                "unresolved_category",
                "unresolved_tag",
                "unresolved_publication_site",
                "unresolved_canonical_site",
            },
        )
        self.assertNotIn("author", form.initial)
        self.assertNotIn("category", form.initial)
        self.assertEqual(form.initial["tags"], [self.tag.pk])
        self.assertEqual(form.initial["publication_sites"], [])
        self.assertEqual(form.source_reference_data["author"], "missing-author")
        self.assertEqual(form.source_reference_data["publication_sites"], ["missing-site"])

    def test_review_form_requires_existing_choices_and_canonical_selected_site(self):
        parsed = validate_blog_import(payload(tags=["django"])).parsed
        references = resolve_blog_import_references(parsed)
        valid_data = {
            "author": str(self.author.pk),
            "category": str(self.category.pk),
            "tags": [str(self.tag.pk)],
            "publication_sites": ["vanta_admin"],
            "canonical_site": "vanta_admin",
            "draft_confirmation": "on",
        }

        form = BlogArticleImportReviewForm(data=valid_data, parsed=parsed, references=references)

        self.assertTrue(form.is_valid(), form.errors)
        reviewed = form.reviewed_references()
        self.assertEqual(reviewed["author"], self.author)
        self.assertEqual(reviewed["category"], self.category)
        self.assertEqual(reviewed["tags"], (self.tag,))
        self.assertEqual(reviewed["publication_sites"], ("vanta_admin",))
        self.assertEqual(reviewed["canonical_site"], "vanta_admin")

        invalid_data = deepcopy(valid_data)
        invalid_data["publication_sites"] = ["my_website"]
        invalid_data["canonical_site"] = "vanta_admin"
        invalid_form = BlogArticleImportReviewForm(
            data=invalid_data,
            parsed=parsed,
            references=references,
        )
        self.assertFalse(invalid_form.is_valid())
        self.assertIn("The canonical site must be one of the publication sites.", invalid_form.errors["canonical_site"])

    def test_review_form_rejects_mapping_and_creating_a_category_together(self):
        source = payload(category='proposed-category')
        source['version'] = 2
        source['article']['category'] = {
            'name': 'Proposed category',
            'slug': 'proposed-category',
        }
        parsed = validate_blog_import(source).parsed
        references = resolve_blog_import_references(parsed)
        form = BlogArticleImportReviewForm(
            data={
                'author': str(self.author.pk),
                'category': str(self.category.pk),
                'create_category': 'on',
                'publication_sites': ['vanta_admin'],
                'canonical_site': 'vanta_admin',
                'draft_confirmation': 'on',
            },
            parsed=parsed,
            references=references,
        )

        self.assertFalse(form.is_valid())
        self.assertIn(
            'Choose an existing category or create the proposed category, not both.',
            form.errors['create_category'],
        )

    def test_change_files_action_does_not_require_creation_fields(self):
        form = BlogArticleImportReviewForm(data={"action": "change_files"}, action="change_files")

        self.assertTrue(form.is_valid(), form.errors)
