# Generated by Django 6.0.7 on 2026-07-31 22:16

import apps.blog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('original', models.ImageField(upload_to=apps.blog.models.blog_original_upload_path)),
                ('rendition_480', models.ImageField(blank=True, upload_to=apps.blog.models.blog_rendition_upload_path)),
                ('rendition_800', models.ImageField(blank=True, upload_to=apps.blog.models.blog_rendition_upload_path)),
                ('rendition_1200', models.ImageField(blank=True, upload_to=apps.blog.models.blog_rendition_upload_path)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_decorative', models.BooleanField(default=False)),
                ('caption_title', models.CharField(blank=True, max_length=255)),
                ('caption_text', models.CharField(blank=True, max_length=255)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('processing_error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blog_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('unpublished', 'Unpublished')], default='draft', max_length=20)),
                ('type', models.CharField(choices=[('article', 'Article'), ('guide', 'Guide'), ('tutorial', 'Tutorial'), ('comparison', 'Comparison'), ('top_list', 'Top list')], default='article', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('public_author_name', models.CharField(blank=True, max_length=120)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_reviewed_on', models.DateField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('canonical_site_slug', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blog_posts', to=settings.AUTH_USER_MODEL)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_posts', to='blog.blogimage')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-published_at', '-pk'],
                'permissions': [('organize_blogpost', 'Can organize blog posts'), ('publish_blogpost', 'Can publish blog posts'), ('unpublish_blogpost', 'Can unpublish blog posts')],
            },
        ),
        migrations.CreateModel(
            name='BlogLinkGroupBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('label', models.CharField(max_length=200)),
                ('links', models.JSONField(default=list)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='blog.blogpost')),
            ],
            options={
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogImageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('is_expandable', models.BooleanField(default=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_blocks', to='blog.blogimage')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='blog.blogpost')),
            ],
            options={
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogCodeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('code', models.TextField()),
                ('language', models.CharField(choices=[('text', 'Plain text'), ('python', 'Python'), ('shell', 'Shell'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('json', 'JSON'), ('sql', 'SQL'), ('dart', 'Dart')], default='text', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='blog.blogpost')),
            ],
            options={
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogChecklistBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('marker', models.CharField(choices=[('checkmark', 'Checkmark'), ('square', 'Square checkbox')], default='checkmark', max_length=20)),
                ('items', models.JSONField(default=list)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='blog.blogpost')),
            ],
            options={
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogCalloutBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('callout_type', models.CharField(choices=[('note', 'Note'), ('tip', 'Tip'), ('warning', 'Warning')], default='note', max_length=12)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='blog.blogpost')),
            ],
            options={
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPostRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='blog.blogpost')),
                ('related_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_related_links', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'related article',
                'verbose_name_plural': 'related articles',
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_posts',
            field=models.ManyToManyField(blank=True, related_name='related_to_posts', through='blog.BlogPostRelated', through_fields=('post', 'related_post'), to='blog.blogpost'),
        ),
        migrations.CreateModel(
            name='BlogRichTextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('body', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'rich text',
                'verbose_name_plural': 'rich text blocks',
            },
        ),
        migrations.CreateModel(
            name='BlogSourceLinkBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('label', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='blog.blogpost')),
            ],
            options={
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.blogtag'),
        ),
        migrations.CreateModel(
            name='BlogHeadingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(choices=[(2, 'H2'), (3, 'H3')], default=2)),
                ('text', models.CharField(max_length=200)),
                ('anchor', models.SlugField(max_length=220)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='blog.blogpost')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('parent', 'anchor'), name='blog_unique_heading_anchor')],
            },
        ),
        migrations.CreateModel(
            name='BlogPostPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_slug', models.CharField(max_length=40)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'publication',
                'verbose_name_plural': 'publications',
                'ordering': ['site_slug'],
                'indexes': [models.Index(fields=['site_slug'], name='blog_blogpo_site_sl_18f83d_idx')],
                'constraints': [models.UniqueConstraint(fields=('post', 'site_slug'), name='blog_one_publication_per_site')],
            },
        ),
        migrations.AddConstraint(
            model_name='blogpostrelated',
            constraint=models.UniqueConstraint(fields=('post', 'related_post'), name='blog_one_related_post'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', 'published_at'], name='blog_blogpo_status_aa5436_idx'),
        ),
    ]
