# Generated by Django 6.0.7 on 2026-07-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsourcelinkblock',
            name='label',
            field=models.CharField(default='Source:', max_length=200),
        ),
    ]
