# Generated by Django 6.0.7 on 2026-07-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogsourcelinkblock_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogchecklistblock',
            name='marker',
            field=models.CharField(choices=[('checkmark', 'Checkmark'), ('square', 'Square checkbox'), ('arrow', 'Arrow')], default='checkmark', max_length=20),
        ),
    ]
