# Generated by Django 6.0.7 on 2026-08-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_authorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='public_author_name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='articles',
                to='blog.authorprofile',
                verbose_name='Author',
            ),
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='public_author_name',
        ),
    ]
