# Generated by Django 6.0.7 on 2026-08-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_authorprofile_public_author_name_blogpost_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorprofile',
            options={'ordering': ['public_author_name', 'pk'], 'verbose_name': 'author', 'verbose_name_plural': 'authors'},
        ),
    ]
