# Generated by Django 6.0.7 on 2026-08-01 19:31

import django.db.models.deletion
from django.db import migrations, models


def require_categories(apps, schema_editor):
    BlogPost = apps.get_model('blog', 'BlogPost')
    if BlogPost.objects.filter(category__isnull=True).exists():
        raise RuntimeError(
            'Assign a category to every blog article before applying this migration.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_authorprofile_options'),
    ]

    operations = [
        migrations.RunPython(require_categories, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.blogcategory'),
        ),
    ]
