# Generated by Django 6.0.7 on 2026-08-02 00:50

import apps.blog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_bloginternallinkblock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImageComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('first_original', models.ImageField(upload_to=apps.blog.models.blog_comparison_original_upload_path)),
                ('first_rendition_480', models.ImageField(blank=True, upload_to=apps.blog.models.blog_comparison_rendition_upload_path)),
                ('first_rendition_800', models.ImageField(blank=True, upload_to=apps.blog.models.blog_comparison_rendition_upload_path)),
                ('first_rendition_1200', models.ImageField(blank=True, upload_to=apps.blog.models.blog_comparison_rendition_upload_path)),
                ('first_width', models.PositiveIntegerField(default=0)),
                ('first_height', models.PositiveIntegerField(default=0)),
                ('first_alt_text', models.CharField(max_length=255)),
                ('first_processing_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('first_processing_error', models.CharField(blank=True, max_length=255)),
                ('second_original', models.ImageField(upload_to=apps.blog.models.blog_comparison_original_upload_path)),
                ('second_rendition_480', models.ImageField(blank=True, upload_to=apps.blog.models.blog_comparison_rendition_upload_path)),
                ('second_rendition_800', models.ImageField(blank=True, upload_to=apps.blog.models.blog_comparison_rendition_upload_path)),
                ('second_rendition_1200', models.ImageField(blank=True, upload_to=apps.blog.models.blog_comparison_rendition_upload_path)),
                ('second_width', models.PositiveIntegerField(default=0)),
                ('second_height', models.PositiveIntegerField(default=0)),
                ('second_alt_text', models.CharField(max_length=255)),
                ('second_processing_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('second_processing_error', models.CharField(blank=True, max_length=255)),
                ('caption_title', models.CharField(blank=True, max_length=255)),
                ('caption_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blog_image_comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comparison image',
                'verbose_name_plural': 'comparison images',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='BlogImageComparisonBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_blocks', to='blog.blogimagecomparison')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='blog.blogpost')),
            ],
            options={
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
    ]
