# Generated by Django 6.0.7 on 2026-08-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blogimage_is_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
