# Generated by Django 6.0.7 on 2026-08-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_blogpost_content_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='type',
            field=models.CharField(choices=[('article', 'Article'), ('guide', 'Guide'), ('comparison', 'Comparison'), ('top_list', 'Top list'), ('showcase', 'Showcase')], default='article', max_length=20),
        ),
    ]
