# Generated by Django 6.0.7 on 2026-08-03 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_add_showcase_article_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogFAQBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('items', models.JSONField(blank=True, default=list)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ blocks',
            },
        ),
    ]
