# Generated by Django 6.0.7 on 2026-08-03 11:46

import apps.blog.models
import apps.blog.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blogfaqblock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticleImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_filename', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('warnings', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_article_import', to='blog.blogpost')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_article_imports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogArticleImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_name', models.CharField(max_length=255)),
                ('file', models.FileField(storage=apps.blog.storage.get_private_blog_import_storage, upload_to=apps.blog.models.blog_import_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='blog.blogarticleimport')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('import_session', 'selected_name'), name='blog_import_file_selected_name')],
            },
        ),
    ]
