# Generated by Django 6.0.7 on 2026-08-03 13:08

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_blogarticleimport_blogarticleimportfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='rendition_1600',
            field=models.ImageField(blank=True, upload_to=apps.blog.models.blog_rendition_upload_path),
        ),
        migrations.AddField(
            model_name='blogimagecomparison',
            name='first_rendition_1600',
            field=models.ImageField(blank=True, upload_to=apps.blog.models.blog_comparison_rendition_upload_path),
        ),
        migrations.AddField(
            model_name='blogimagecomparison',
            name='second_rendition_1600',
            field=models.ImageField(blank=True, upload_to=apps.blog.models.blog_comparison_rendition_upload_path),
        ),
    ]
