# Generated by Django 6.0.7 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_blogimage_rendition_1600_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticleimport',
            name='permanent_cleanup_paths',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
