# Generated by Django 6.1 on 2026-08-09 23:30

from html.parser import HTMLParser

from django.db import migrations, models


class _ReaderTextParser(HTMLParser):
    BOUNDARY_TAGS = frozenset({
        'address', 'article', 'aside', 'blockquote', 'br', 'dd', 'div', 'dl',
        'dt', 'figcaption', 'figure', 'footer', 'h1', 'h2', 'h3', 'h4', 'h5',
        'h6', 'header', 'hr', 'li', 'main', 'nav', 'ol', 'p', 'pre', 'section',
        'table', 'tbody', 'td', 'tfoot', 'th', 'thead', 'tr', 'ul',
    })

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.parts = []

    def handle_starttag(self, tag, attrs):
        if tag in self.BOUNDARY_TAGS:
            self.parts.append(' ')

    def handle_startendtag(self, tag, attrs):
        if tag in self.BOUNDARY_TAGS:
            self.parts.append(' ')

    def handle_endtag(self, tag):
        if tag in self.BOUNDARY_TAGS:
            self.parts.append(' ')

    def handle_data(self, data):
        self.parts.append(data)


def normalize_text(*values):
    parser = _ReaderTextParser()
    parser.feed(' '.join(str(value or '') for value in values))
    parser.close()
    text = ''.join(parser.parts).replace('\xa0', ' ')
    return ' '.join(text.split())


def backfill_search_body_text(apps, schema_editor):
    database = schema_editor.connection.alias
    BlogPost = apps.get_model('blog', 'BlogPost')
    BlogHeadingBlock = apps.get_model('blog', 'BlogHeadingBlock')
    BlogRichTextBlock = apps.get_model('blog', 'BlogRichTextBlock')
    BlogFAQBlock = apps.get_model('blog', 'BlogFAQBlock')
    BlogChecklistBlock = apps.get_model('blog', 'BlogChecklistBlock')
    BlogCalloutBlock = apps.get_model('blog', 'BlogCalloutBlock')
    BlogSourceLinkBlock = apps.get_model('blog', 'BlogSourceLinkBlock')
    BlogLinkGroupBlock = apps.get_model('blog', 'BlogLinkGroupBlock')
    BlogInternalLinkBlock = apps.get_model('blog', 'BlogInternalLinkBlock')

    for post_id in BlogPost.objects.using(database).values_list('pk', flat=True).iterator():
        parts = []
        parts.extend(
            BlogHeadingBlock.objects.using(database)
            .filter(parent_id=post_id)
            .values_list('text', flat=True)
        )
        parts.extend(
            BlogRichTextBlock.objects.using(database)
            .filter(parent_id=post_id)
            .values_list('body', flat=True)
        )
        for items in (
            BlogFAQBlock.objects.using(database)
            .filter(parent_id=post_id)
            .values_list('items', flat=True)
        ):
            if isinstance(items, list):
                parts.extend(
                    value
                    for item in items
                    if isinstance(item, dict)
                    for value in (item.get('question', ''), item.get('answer', ''))
                )
        for items in (
            BlogChecklistBlock.objects.using(database)
            .filter(parent_id=post_id)
            .values_list('items', flat=True)
        ):
            if isinstance(items, list):
                parts.extend(items)
        for title, body in (
            BlogCalloutBlock.objects.using(database)
            .filter(parent_id=post_id)
            .values_list('title', 'body')
        ):
            parts.extend((title, body))
        for label, note in (
            BlogSourceLinkBlock.objects.using(database)
            .filter(parent_id=post_id)
            .values_list('label', 'note')
        ):
            parts.extend((label, note))
        for label, links in (
            BlogLinkGroupBlock.objects.using(database)
            .filter(parent_id=post_id)
            .values_list('label', 'links')
        ):
            parts.append(label)
            if isinstance(links, list):
                parts.extend(
                    link.get('label', '')
                    for link in links
                    if isinstance(link, dict)
                )
        for label, note in (
            BlogInternalLinkBlock.objects.using(database)
            .filter(parent_id=post_id)
            .values_list('label', 'note')
        ):
            parts.extend((label, note))
        BlogPost.objects.using(database).filter(pk=post_id).update(
            search_body_text=normalize_text(*parts),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_blogarticleimport_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='search_body_text',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.RunPython(backfill_search_body_text, migrations.RunPython.noop),
    ]
