# Generated by Django 6.1 on 2026-08-10 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_add_blog_search_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEmbedSharingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('x', 'X'), ('reddit', 'Reddit')], max_length=12)),
                ('url', models.URLField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='blog.blogpost')),
            ],
            options={
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
    ]
