# Generated by Django 6.1 on 2026-08-13 11:58

import django.db.models.deletion
from django.db import migrations, models


def backfill_taxonomy_websites(apps, schema_editor):
    BlogSite = apps.get_model('blog', 'BlogSite')
    BlogCategory = apps.get_model('blog', 'BlogCategory')
    BlogCategorySite = apps.get_model('blog', 'BlogCategorySite')
    BlogTag = apps.get_model('blog', 'BlogTag')
    BlogTagSite = apps.get_model('blog', 'BlogTagSite')

    site_slugs = {'vanta_admin'}
    site_slugs.update(
        apps.get_model('blog', 'BlogPostPublication').objects.values_list('site_slug', flat=True)
    )
    BlogSite.objects.bulk_create(
        [BlogSite(slug=slug) for slug in sorted(site_slugs)],
        ignore_conflicts=True,
    )
    for category in BlogCategory.objects.all():
        assigned = {'vanta_admin'}
        assigned.update(category.posts.values_list('publications__site_slug', flat=True))
        BlogCategorySite.objects.bulk_create(
            [BlogCategorySite(taxonomy=category, site_id=slug) for slug in assigned if slug],
            ignore_conflicts=True,
        )
    for tag in BlogTag.objects.all():
        assigned = {'vanta_admin'}
        assigned.update(tag.posts.values_list('publications__site_slug', flat=True))
        BlogTagSite.objects.bulk_create(
            [BlogTagSite(taxonomy=tag, site_id=slug) for slug in assigned if slug],
            ignore_conflicts=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_blogembedsharingblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSite',
            fields=[
                ('slug', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'website',
                'verbose_name_plural': 'websites',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='BlogCategorySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_assignments', to='blog.blogcategory')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogsite')),
            ],
            options={
                'verbose_name': 'category website',
                'verbose_name_plural': 'category websites',
            },
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='websites',
            field=models.ManyToManyField(blank=True, related_name='categories', through='blog.BlogCategorySite', to='blog.blogsite'),
        ),
        migrations.CreateModel(
            name='BlogTagSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogsite')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_assignments', to='blog.blogtag')),
            ],
            options={
                'verbose_name': 'tag website',
                'verbose_name_plural': 'tag websites',
            },
        ),
        migrations.AddField(
            model_name='blogtag',
            name='websites',
            field=models.ManyToManyField(blank=True, related_name='tags', through='blog.BlogTagSite', to='blog.blogsite'),
        ),
        migrations.RunPython(backfill_taxonomy_websites, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='blogcategorysite',
            constraint=models.UniqueConstraint(fields=('taxonomy', 'site'), name='blog_category_site_unique'),
        ),
        migrations.AddConstraint(
            model_name='blogtagsite',
            constraint=models.UniqueConstraint(fields=('taxonomy', 'site'), name='blog_tag_site_unique'),
        ),
    ]
