from __future__ import annotations

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from apps.core.sites import get_blog_site_slug_choices

from .import_contract import MAX_SOURCE_BYTES
from .forms import BlogTagCheckboxSelectMultiple
from .models import AuthorProfile, BlogCategory, BlogTag


MAX_IMAGE_FILE_COUNT = 50
MAX_IMAGE_AGGREGATE_BYTES = 150 * 1024 * 1024


class MultipleFileInput(forms.ClearableFileInput):
    """A normal Django file input that returns all selected files."""

    allow_multiple_selected = True


class MultipleFileField(forms.FileField):
    """Validate each selected upload while preserving a list-valued field."""

    widget = MultipleFileInput

    def clean(self, data, initial=None):
        if not data:
            if self.required:
                return super().clean(data, initial)
            return []
        if not isinstance(data, (list, tuple)):
            data = [data]
        return [super().clean(item, initial) for item in data]


class BlogArticleImportUploadForm(forms.Form):
    source_file = forms.FileField(
        label=_('Article JSON file'),
        help_text=_('Choose one article file generated by the writing workflow.'),
        widget=forms.ClearableFileInput(attrs={'accept': '.json,application/json'}),
    )
    image_files = MultipleFileField(
        label=_('Local images'),
        required=False,
        help_text=_('Choose the local image files referenced by the article.'),
        widget=MultipleFileInput(
            attrs={
                'accept': ','.join(
                    (
                        '.jpg',
                        '.jpeg',
                        '.png',
                        '.webp',
                        'image/jpeg',
                        'image/png',
                        'image/webp',
                    )
                )
            }
        ),
    )

    def clean_source_file(self):
        source_file = self.cleaned_data['source_file']
        if getattr(source_file, 'size', 0) > MAX_SOURCE_BYTES:
            raise ValidationError(_('The article JSON file is too large.'))
        return source_file

    def clean_image_files(self):
        image_files = list(self.cleaned_data.get('image_files') or [])
        if len(image_files) > MAX_IMAGE_FILE_COUNT:
            raise ValidationError(
                _('Choose no more than %(count)s local image files.')
                % {'count': MAX_IMAGE_FILE_COUNT}
            )
        aggregate_size = sum(max(0, int(getattr(upload, 'size', 0) or 0)) for upload in image_files)
        if aggregate_size > MAX_IMAGE_AGGREGATE_BYTES:
            raise ValidationError(_('The selected image files are too large together.'))
        return image_files


class BlogArticleImportReviewForm(forms.Form):
    create_category = forms.BooleanField(required=False)
    create_tags = forms.MultipleChoiceField(required=False, widget=forms.CheckboxSelectMultiple)
    expand_taxonomy_websites = forms.BooleanField(
        required=False,
        label=_('Add missing website availability to the selected existing terms.'),
    )
    author = forms.ModelChoiceField(
        label=_('Author'),
        queryset=AuthorProfile.objects.none(),
        required=True,
    )
    category = forms.ModelChoiceField(
        label=_('Category'),
        queryset=BlogCategory.objects.none(),
        required=True,
    )
    tags = forms.ModelMultipleChoiceField(
        label=_('Tags'),
        queryset=BlogTag.objects.none(),
        required=False,
        widget=BlogTagCheckboxSelectMultiple(attrs={'class': 'blog-tag-picker__choices'}),
    )
    publication_sites = forms.MultipleChoiceField(
        label=_('Publication sites'),
        required=True,
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'blog-publication-picker__choices'}),
    )
    canonical_site = forms.ChoiceField(
        label=_('Canonical site'),
        required=True,
    )
    draft_confirmation = forms.BooleanField(
        label=_('I confirm that a new draft will be created.'),
        required=True,
    )

    ACTIONS = frozenset({'create', 'change_files', 'cancel'})

    def __init__(
        self,
        *args,
        review=None,
        references=None,
        parsed=None,
        action=None,
        **kwargs,
    ):
        super().__init__(*args, **kwargs)
        self.review = review
        self.references = references or getattr(review, 'references', None)
        self.parsed = parsed or getattr(review, 'parsed', None)
        submitted_action = action or (self.data.get('action') if self.is_bound else None)
        self.action = submitted_action if submitted_action in self.ACTIONS else 'create'

        self.fields['author'].queryset = AuthorProfile.objects.order_by('public_author_name', 'pk')
        self.fields['category'].queryset = BlogCategory.objects.order_by('name', 'pk')
        self.fields['tags'].queryset = BlogTag.objects.order_by('name', 'pk')
        site_choices = get_blog_site_slug_choices()
        self.fields['publication_sites'].choices = site_choices
        self.fields['canonical_site'].choices = site_choices

        def taxonomy_label(term):
            websites = ', '.join(str(site) for site in term.websites.all()) or str(_('No websites'))
            return f'{term.name} — {websites}'

        self.fields['category'].label_from_instance = taxonomy_label
        self.fields['tags'].label_from_instance = taxonomy_label
        unresolved_tags = []
        article = getattr(self.parsed, 'article', None)
        if article:
            if article.category.name and getattr(self.references, 'category', None) is None:
                self.fields['create_category'].label = _(
                    'Create proposed category “%(name)s” (%(slug)s)'
                ) % {'name': article.category.name, 'slug': article.category.slug}
                self.fields['category'].required = False
            else:
                self.fields['create_category'].widget = forms.HiddenInput()
            resolved_tag_slugs = {
                tag.slug for tag in tuple(getattr(self.references, 'tags', ()) or ())
            }
            unresolved_tags = [tag for tag in article.tags if tag.name and tag.slug not in resolved_tag_slugs]
        self.fields['create_tags'].choices = [
            (tag.slug, f'{tag.name} ({tag.slug})') for tag in unresolved_tags
        ]

        if self.action != 'create':
            for field_name in ('author', 'category', 'publication_sites', 'canonical_site', 'draft_confirmation'):
                self.fields[field_name].required = False

        self.source_reference_data = self._build_source_reference_data()
        self.unresolved_references = tuple(
            getattr(self.references, 'unresolved', ()) if self.references is not None else ()
        )
        self._set_initial_values()

    def _build_source_reference_data(self):
        if self.parsed is None:
            return {}
        article = self.parsed.article
        return {
            'author': article.author.slug,
            'category': article.category.slug,
            'tags': [tag.slug for tag in article.tags],
            'publication_sites': list(article.publication_sites),
            'canonical_site': article.canonical_site,
            'create_category': False,
            'create_tags': [],
            'expand_taxonomy_websites': False,
        }

    def _set_initial_values(self):
        if self.references is None:
            return
        author = getattr(self.references, 'author', None)
        category = getattr(self.references, 'category', None)
        tags = tuple(getattr(self.references, 'tags', ()) or ())
        sites = tuple(getattr(self.references, 'resolved_publication_sites', ()) or ())
        canonical_site = getattr(self.references, 'resolved_canonical_site', None)
        if author is not None:
            self.initial['author'] = author.pk
        if category is not None:
            self.initial['category'] = category.pk
        self.initial['tags'] = [tag.pk for tag in tags]
        self.initial['publication_sites'] = list(sites)
        if canonical_site in sites:
            self.initial['canonical_site'] = canonical_site
        elif len(sites) == 1:
            self.initial['canonical_site'] = sites[0]

    def clean_publication_sites(self):
        values = tuple(dict.fromkeys(self.cleaned_data.get('publication_sites') or ()))
        return values

    def clean_canonical_site(self):
        value = self.cleaned_data.get('canonical_site', '')
        if value and value not in set(self.cleaned_data.get('publication_sites') or ()):
            raise ValidationError(_('The canonical site must be one of the publication sites.'))
        return value

    def clean(self):
        cleaned_data = super().clean()
        if self.action != 'create':
            return cleaned_data
        selected_sites = set(cleaned_data.get('publication_sites') or ())
        canonical_site = cleaned_data.get('canonical_site')
        if canonical_site and canonical_site not in selected_sites:
            self.add_error('canonical_site', _('The canonical site must be one of the publication sites.'))
        category = cleaned_data.get('category')
        create_category = cleaned_data.get('create_category')
        if category and create_category:
            self.add_error(
                'create_category',
                _('Choose an existing category or create the proposed category, not both.'),
            )
        elif not category and not create_category:
            self.add_error('category', _('Choose an existing category or confirm creation.'))
        return cleaned_data

    def reviewed_references(self):
        """Return only the choices that the final service may accept."""

        if not self.is_valid():
            raise ValueError('Call reviewed_references() only after the form is valid.')
        return {
            'author': self.cleaned_data.get('author'),
            'category': self.cleaned_data.get('category'),
            'tags': tuple(self.cleaned_data.get('tags') or ()),
            'publication_sites': tuple(self.cleaned_data.get('publication_sites') or ()),
            'canonical_site': self.cleaned_data.get('canonical_site') or None,
            'create_category': self.cleaned_data.get('create_category', False),
            'create_tags': tuple(self.cleaned_data.get('create_tags') or ()),
            'expand_taxonomy_websites': self.cleaned_data.get('expand_taxonomy_websites', False),
        }
